name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Build and deploy
      run: |
        
        # Configure git
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        
        # Deploy to gh-pages branch
        git checkout gh-pages
        git add .
        git commit -m "Deploy updated files"
        git push origin gh-pages
